### ISSUE TITLE
Update examples, register examples for multiple IDEs

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/CMSIS-View#110]
This pack contains multiple examples, some of them are outdated (i.e. the Fault example for B-U585I-IOT02A).

As the example contains different project formats, it should be possible to register it for multiple IDEs, i.e. `csolution` and `uv` as shown here: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_examples_pg.html#element_example_project_env

We should try this to ensure that VS Code CMSIS Solution can cope with it.

Relates to https://github.com/ARM-software/vscode-cmsis-csolution/issues/100

**Comment by MiloradCvjetkovic** [comment]
Addressed and available in the `main` branch .
