### ISSUE TITLE
In `Component_Viewer.xsd` the `bold` attribute does not support expression evaluation resolving to boolean

### ISSUE THREAD

**Issue by MiloradCvjetkovic** [ARM-software/CMSIS-View#52]
Although in the documentation for `bold` attribute at https://arm-software.github.io/CMSIS-View/latest/elem_item.html 
under **Description** it is written "Output in the Value column is displayed in bold when expression result is not 0. Default value is 0. See also alert and bold output."

that does not appear so as 'bold' attribute is specified in the **Component_Viewer.xsd** as:
"<xs:attribute name="bold"     type="xs:boolean"/>"

whereas for example 'alert' attribute is specified as:
"<xs:attribute name="alert"    type="xs:string" />"

In the **Component_Viewer.xsd** history for the date  23. Feb 2018 it is mentioned:
"- updated attribute alert to xs:string to support expression evaluation resolving to boolean"

however, it does not look like the same thing was done to the `bold` attribute also.

**Comment by jkrech** [comment]
@MiloradCvjetkovic have you tried whether it would be actually supported already by the tools?
