### ISSUE TITLE
tags are following inconsistent naming format

### ISSUE THREAD

**Issue by aethaniel** [ARM-software/CMSIS-View#75]
Hi, 
Is it possible to have the tags being more consistent?
Most of people expect a product release to be vx.y.z without the decoration I see in the tags here.
Thanks

**Comment by jkrech** [comment]
Hi @aethaniel,
the background for this tag formatting is that this repository contains two parts:
a) eventlist tool
b) embedded software shipped in a pack
The extended tags are used to keep them separate.
Assuming that people will clone this repository for b) only the tags prepended with pack/ are relevant.

**Comment by aethaniel** [comment]
Hi @jkrech, 
Thanks for your answer but we don't share same point of view.
From outside, people see (or shall see) only one product: CMSIS-View. So, even if I understand your position, I think the one we have from outside is more important. 
That means we expect tags being consistent (1.0.0/1.1.0/etc...), as I reported here.
If you intend to have 2 products in this repo, I would suggest to split into 2 individual repos.

My 2 cents,
Thibaut

**Comment by aethaniel** [comment]
@JonatanAntoni, we are only using this repository as third party code for the Event Recorder. As I'm not involved into this task, I didn't see this repo contains various things, all related.
We fixed a bug in our content deployment tool and whatever you do in term of tags here will be fine for us. Just make them simple for end users ;-)

**Comment by JonatanAntoni** [comment]
Not sure if I understand this request. Tags are as they are, they are consistent. I appreciate that having two independent artifacts with their individual release cycles might be confusing. This can't be changed easily. Hence I'd consider this as *won't fix*.
