### ISSUE TITLE
VSCode integration and CI/CD

### ISSUE THREAD

**Issue by jankap** [ARM-software/CMSIS-View#98]
I highly appreciate that EventRecorder officially got open-sourced and can be used without Keil now, too.

We have a valid Keil license, but sometimes we would like to use the EventRecorder in VSCode, and especially in CI/CD environments to test timings etc. 

Are there any recommendations how to do so?

Thanks!

**Comment by jkrech** [comment]
Hi @jankap did you take a look at the example here: 
https://github.com/ARM-software/CMSIS-View/tree/main/Examples/EventStatistic
The README.md gives you the instructions how to run the `eventlist` cli tool. At this point this relies on running the application on a FastModel. This should give you a flavor of where we want to get to however we are currently lacking the reading of the event buffer from the target memory via a debugger connection.

**Comment by jkrech** [comment]
Since I did not receive any follow up questions, I am now closing this issue.
